# Generated by Django 5.2.17 on 2026-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_lineages',
            field=models.JSONField(blank=True, default=list, help_text='Klíče rodů, které uživatel vidí (např. novakovi). Prázdné = nevidí žádný rod. Admin vidí všechny.'),
        ),
    ]
