# Generated by Django 5.2.17 on 2026-09-29 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(db_index=True, max_length=255)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('quote', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start', 'created_at'],
            },
        ),
    ]
